from agent_k.utils.listable_class import ListableClass


class MinModHyperCols(ListableClass):
    GROUP_ID = "group_id"
    MS = "ms"
    MS_NAME = "ms_name"
    MS_NAME_PREPROCESSED = "ms_name_preprocessed"
    MS_TYPE = "ms_type"
    MS_RANK = "ms_rank"
    COUNTRY = "country"
    STATE_OR_PROVINCE = "state_or_province"
    LOC_CRS = "loc_crs"
    LOC_WKT = "loc_wkt"
    TOT_CONTAINED_METAL = "tot_contained_metal"
    TOT_TONNAGE = "total_tonnage"
    TOT_GRADE = "total_grade"
    TOP1_DEPOSIT_TYPE = "top1_deposit_type"
    TOP1_DEPOSIT_GROUP = "top1_deposit_group"
    TOP1_DEPOSIT_ENVIRONMENT = "top1_deposit_environment"
    TOP1_DEPOSIT_CLASSIFICATION_CONFIDENCE = "top1_deposit_classification_confidence"
    TOP1_DEPOSIT_CLASSIFICATION_SOURCE = "top1_deposit_classification_source"
    SOURCE_VALUE = "source.value"
    RECORD_VALUE = "record.value"
    RECORD_VALUE_IMPUTED = "record.value_imputed"
    DOWNLOADED_PDF = "downloaded_pdf"
